version: "3.7"
services:
  minio:
    container_name: isis-server_minio
    image: "minio/minio:latest"
    environment:
      MINIO_ACCESS_KEY: abc
      MINIO_SECRET_KEY: "12345678"
    command:
      - server
      - /data
    volumes: ["./data:/data"]
    ports: ["9000:9000"]

  isis_server:
    build: .
    image: isis-server
    container_name: isis-server
    command: "bash -lc '.python/bin/gunicorn -c gunicorn.conf.py --reload isis_server:app'"
    working_dir: /app
    volumes: [".:/app"]
    ports: ["8000:8000"]
